### ISSUE TITLE
Please provide the LICENSE for the imported files

### ISSUE THREAD

**Issue by johanbrandhorst** [moul/pb#2]
It appears you have copy-pasted most of the contents of https://github.com/moul/pb/tree/master/a_bit_of_everything/lib from the https://github.com/grpc-ecosystem/grpc-gateway project without including the necessary LICENSE. Could you please add a copy of the license to this repository?

**Comment by moul** [comment]
yes, sorry for this, and sorry for being late

thank you for the message, I'll be more rigorous now

**Comment by johanbrandhorst** [comment]
Please don't close this issue until it has been fixed, so that I can verify that the fix is sufficient.

**Comment by moul** [comment]
Changes applied, please checkout master
