### ISSUE TITLE
Please provide LICENSE file

### ISSUE THREAD

**Issue by lake-of-dreams** [moul/pb#3]
Possible to include the license file in this repository?

**Comment by moul** [comment]
yes, sorry

and thank you very much for the message 👍

**Comment by gongomgra** [comment]
Hi @moul, I can't find the license in the repo. Can you upload it and also tell us under which license is your code published?

**Comment by moul** [comment]
Sorry, the git push command didn't succeed and I closed the term, it's not pushed, you can checkout master

**Comment by gongomgra** [comment]
Great, I see the MIT license file now. Thanks!
